name: rocm-core

on:
  push:
    paths:
      - 'stage1/rocm-core/*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: '手动构建rocm-core'
      tags:
        description: '手动构建rocm-core'

jobs:
  loongarch64-build-rocm-core:
    runs-on: [self-hosted, loongarch64-real]
    steps:
    - uses: actions/checkout@v4
      with:
        clean: false
    - name: remove_pkg
      run: sh -c "pacman -Q -q|grep '^rocm'|sudo xargs pacman --noconfirm -R " || true
    - name: install_pkg
      run: echo 'rocm-core no need dep'
    - name: makepkg
      run: makepkg -Cf
      working-directory: ./stage1/rocm-core/
    - name: post-to-localrepo
      run: cp -f *.pkg.tar.gz /opt/localrepo
      working-directory: ./stage1/rocm-core/
  amd64-build-rocm-core:
    runs-on: [self-hosted, amd64-real]
    steps:
    - uses: actions/checkout@v4
      with:
        clean: false
    - name: remove_pkg
      run: sh -c "pacman -Q -q|grep '^rocm'|sudo xargs pacman --noconfirm -R " || true
    - name: install_pkg
      run: echo 'rocm-core no need dep'
    - name: makepkg
      run: makepkg -Cf
      working-directory: ./stage1/rocm-core/
    - name: post-to-localrepo
      run: cp -f *.pkg.tar.gz /opt/localrepo
      working-directory: ./stage1/rocm-core/
