name: rocm-llvm

on:
  push:
    paths:
      - 'stage1/rocm-llvm/*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: '手动构建rocm-llvm'
      tags:
        description: '手动构建rocm-llvm'

jobs:
  loongarch64-build-rocm-llvm:
    runs-on: [self-hosted, loongarch64-real]
    steps:
    - uses: actions/checkout@v4
      clean: false
    - name: remove_pkg
      run: sh -c "pacman -Q -q|grep '^rocm'|sudo xargs pacman --noconfirm -R " || true
    - name: install_pkg
      run: sudo pacman --noconfirm -U /opt/localrepo/rocm-core*.tar.gz
    - name: makepkg
      run: makepkg -Cf
      working-directory: ./stage1/rocm-llvm/
    - name: post-to-localrepo
      run: cp -f *.pkg.tar.gz /opt/localrepo
      working-directory: ./stage1/rocm-llvm/
  amd64-build-rocm-llvm:
    runs-on: [self-hosted, amd64-real]
    steps:
    - uses: actions/checkout@v4
      clean: false
    - name: remove_pkg
      run: sh -c "pacman -Q -q|grep '^rocm'|sudo xargs pacman --noconfirm -R " || true
    - name: install_pkg
      run: sudo pacman --noconfirm -U /opt/localrepo/rocm-core*.tar.gz
    - name: makepkg
      run: makepkg -Cf
      working-directory: ./stage1/rocm-llvm/
    - name: post-to-localrepo
      run: cp -f *.pkg.tar.gz /opt/localrepo
      working-directory: ./stage1/rocm-llvm/
